# -*- coding: utf-8 -*-
"""DMA_Project Vegan Meat graph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fpK9EsaPZvY4WFmD8d2PX2atBd_8X7K8
"""

import numpy as np
import pandas as pd
import seaborn as sns

from google.colab import files

uploaded = files.upload()

import matplotlib.pyplot as plt

df=pd.read_csv("DonewithDMA.csv")
df

plt.figure(figsize = (15,9))
sns.lineplot(data = df,
                x = 'YEAR',
                y = 'SUM_OF_PRODTYPE',
                hue = 'PRODUCT')
#                 ,style = 'Subject'
# setting labels and title for plot

plt.xlabel("Time (in years)", fontsize = 14)
plt.ylabel("Sum of product type", fontsize = 14)
plt.legend(bbox_to_anchor=(1.02, 1), loc='upper left', borderaxespad=0)
plt.title('Year on year trend of vegan products vs meat products', fontsize = 16)
plt.show()

